name: build-and-publish
run-name: Build and publish by ${{ github.actor }}
on:
  push:
    branches: prod
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13"
      - run: |
          pip install -U pip
          pip install poetry
          poetry install
          python -m build
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: build/
      - uses: actions/deploy-pages@v4.0.5
    permissions:
      contents: read
      pages: write
      id-token: write
